### ISSUE TITLE
Tutorial selection not loading correctly

### ISSUE THREAD

**Issue by jjcrawford** [catmanjan/anutimetable#306] opened 2019-07-25 01:53 UTC
Seems like something is broken in the way the timetable loads users' choices of tutorials.

To reproduce the problem:
1. Add the course ECON3102
2. Observe that there are a large number of tutorials for this course
3. Refresh the page
4. Note that now just one particular tutorial (TutA/2) has been selected

It always loads this particular tutorial, regardless of whether you have picked a different one (or not picked any at all).

Not sure how much this problem affects other courses, too.

**Comment by BishopOfTurkey** [comment] 2019-07-27 02:31
Could you please provide more information on your setup: Browser, Operating System etc
I cannot reproduce this bug with either Firefox, Chrome or Safari. You could also try clearing your cache.

**Comment by jjcrawford** [comment] 2019-07-27 04:27
Hm, when I was experiencing the bug I was just using Chrome, and I also tried it again in incognito mode without any other courses just to narrow down that it wasn’t anything else weird playing up, and it was consistently reproducible — but I just tried it again now (again with Chrome) and the bug no longer appears! I wonder if the update of the course list somehow fixed this.


On 27 Jul 2019, at 12:31 pm, Obi Symons <notifications@github.com<mailto:notifications@github.com>> wrote:


Could you please provide more information on your setup: Browser, Operating System etc
I cannot reproduce this bug with either Firefox, Chrome or Safari. You could also try clearing your cache.

**Comment by BishopOfTurkey** [comment] 2019-07-27 04:30
Closed as no longer an issue.

**Closed by BishopOfTurkey** 2019-07-27 04:30 UTC
